CREATE DATABASE IF NOT EXISTS escuela;
USE escuela;
CREATE TABLE IF NOT EXISTS libros (
  id INT AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(200) NOT NULL,
  autor VARCHAR(150) NOT NULL,
  año_publicacion INT,
  isbn VARCHAR(20) UNIQUE,
  disponible TINYINT(1) NOT NULL DEFAULT 1
);


ALTER TABLE estudiantes MODIFY COLUMN apellido VARCHAR(100) NULL;
